### ISSUE TITLE
ROR Project Kanban Board

### ISSUE THREAD

**Issue by shella12** [shella12/Recipe-app#14]
- [ ] Created tasks on Kanban board based on the [project requirements](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/buisness_requirements.md).
- [ ] Each task has a separate card that:

- [ ] Has a descriptive title.

- [ ] Has the number of points in the [Xpt] prefix. That number indicates the number of points that show how complex the task is. 1 point = 1 hour of estimated work. 

- [ ] Has a description of the task.

We are a team of two namely @shella12  and @ZuhRa-HashiMi . Here is the link to the [Project](https://github.com/users/shella12/projects/10)

**Comment by thecodechaser** [comment]
## STATUS: APPROVED 🟢

## Hi @shella12, and @ZuhRa-HashiMi👋, 

Your project is complete!  There is nothing else to say other than... it's time to close it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/g9582DNuQppxC/giphy-downsized-medium.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
